# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tpmania_gui.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QAbstractItemView, QAbstractScrollArea, QApplication,
    QCheckBox, QComboBox, QDialogButtonBox, QFrame,
    QHeaderView, QLabel, QMainWindow, QPlainTextEdit,
    QProgressBar, QPushButton, QSizePolicy, QSlider,
    QStackedWidget, QTabWidget, QTableWidget, QTableWidgetItem,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(300, 450)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet(u"")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QRect(0, 35, 300, 380))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.HomePage = QWidget()
        self.HomePage.setObjectName(u"HomePage")
        self.MenuButtonFrame = QFrame(self.HomePage)
        self.MenuButtonFrame.setObjectName(u"MenuButtonFrame")
        self.MenuButtonFrame.setGeometry(QRect(20, 195, 260, 155))
        self.MenuButtonFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.MenuButtonFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.menuNavigationWidget = QWidget(self.MenuButtonFrame)
        self.menuNavigationWidget.setObjectName(u"menuNavigationWidget")
        self.menuNavigationWidget.setGeometry(QRect(70, 0, 120, 155))
        self.fileSelection = QPushButton(self.menuNavigationWidget)
        self.fileSelection.setObjectName(u"fileSelection")
        self.fileSelection.setGeometry(QRect(10, 20, 101, 24))
        self.metadataDisplay = QPushButton(self.menuNavigationWidget)
        self.metadataDisplay.setObjectName(u"metadataDisplay")
        self.metadataDisplay.setGeometry(QRect(10, 50, 101, 24))
        self.timingWindows = QPushButton(self.menuNavigationWidget)
        self.timingWindows.setObjectName(u"timingWindows")
        self.timingWindows.setGeometry(QRect(10, 80, 101, 24))
        self.mysteryButton = QPushButton(self.menuNavigationWidget)
        self.mysteryButton.setObjectName(u"mysteryButton")
        self.mysteryButton.setGeometry(QRect(10, 110, 101, 24))
        self.serialPortFrame = QFrame(self.HomePage)
        self.serialPortFrame.setObjectName(u"serialPortFrame")
        self.serialPortFrame.setGeometry(QRect(20, 105, 260, 80))
        self.serialPortFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.serialPortFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.SerialPortLabel = QLabel(self.serialPortFrame)
        self.SerialPortLabel.setObjectName(u"SerialPortLabel")
        self.SerialPortLabel.setGeometry(QRect(0, 0, 120, 40))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.SerialPortLabel.setFont(font)
        self.SerialPortLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.SerialPorts = QComboBox(self.serialPortFrame)
        self.SerialPorts.addItem("")
        self.SerialPorts.setObjectName(u"SerialPorts")
        self.SerialPorts.setGeometry(QRect(140, 8, 100, 24))
        font1 = QFont()
        font1.setPointSize(10)
        self.SerialPorts.setFont(font1)
        self.SerialPorts.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ConfigurePort = QDialogButtonBox(self.serialPortFrame)
        self.ConfigurePort.setObjectName(u"ConfigurePort")
        self.ConfigurePort.setGeometry(QRect(0, 45, 260, 24))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfigurePort.sizePolicy().hasHeightForWidth())
        self.ConfigurePort.setSizePolicy(sizePolicy)
        self.ConfigurePort.setFont(font1)
        self.ConfigurePort.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ConfigurePort.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.ConfigurePort.setOrientation(Qt.Orientation.Horizontal)
        self.ConfigurePort.setStandardButtons(QDialogButtonBox.StandardButton.Retry|QDialogButtonBox.StandardButton.Save)
        self.ConfigurePort.setCenterButtons(True)
        self.stackedWidget.addWidget(self.HomePage)
        self.SettingsPage = QWidget()
        self.SettingsPage.setObjectName(u"SettingsPage")
        self.FileSelectionFrame = QFrame(self.SettingsPage)
        self.FileSelectionFrame.setObjectName(u"FileSelectionFrame")
        self.FileSelectionFrame.setGeometry(QRect(20, 20, 260, 120))
        self.FileSelectionFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.FileSelectionFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.AudioLabel = QLabel(self.FileSelectionFrame)
        self.AudioLabel.setObjectName(u"AudioLabel")
        self.AudioLabel.setGeometry(QRect(0, 40, 80, 16))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.AudioLabel.setFont(font2)
        self.AudioLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.SequenceLabel = QLabel(self.FileSelectionFrame)
        self.SequenceLabel.setObjectName(u"SequenceLabel")
        self.SequenceLabel.setGeometry(QRect(0, 60, 80, 16))
        self.SequenceLabel.setFont(font2)
        self.SequenceLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.HeaderFileSelection = QLabel(self.FileSelectionFrame)
        self.HeaderFileSelection.setObjectName(u"HeaderFileSelection")
        self.HeaderFileSelection.setGeometry(QRect(0, 0, 260, 40))
        self.HeaderFileSelection.setFont(font)
        self.HeaderFileSelection.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.SelectAudioButton = QPushButton(self.FileSelectionFrame)
        self.SelectAudioButton.setObjectName(u"SelectAudioButton")
        self.SelectAudioButton.setGeometry(QRect(202, 40, 16, 16))
        sizePolicy.setHeightForWidth(self.SelectAudioButton.sizePolicy().hasHeightForWidth())
        self.SelectAudioButton.setSizePolicy(sizePolicy)
        font3 = QFont()
        font3.setPointSize(9)
        self.SelectAudioButton.setFont(font3)
        self.SelectAudioButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.SelectAudioButton.setStyleSheet(u"QPushButton{\n"
"	background-color: transparent;\n"
"	border: none;\n"
"	padding: 0;\n"
"}")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentProperties))
        self.SelectAudioButton.setIcon(icon)
        self.SelectAudioButton.setIconSize(QSize(16, 16))
        self.SelectAudioButton.setCheckable(False)
        self.SelectSequenceButton = QPushButton(self.FileSelectionFrame)
        self.SelectSequenceButton.setObjectName(u"SelectSequenceButton")
        self.SelectSequenceButton.setGeometry(QRect(202, 60, 16, 16))
        sizePolicy.setHeightForWidth(self.SelectSequenceButton.sizePolicy().hasHeightForWidth())
        self.SelectSequenceButton.setSizePolicy(sizePolicy)
        self.SelectSequenceButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.SelectSequenceButton.setStyleSheet(u"QPushButton{\n"
"	background-color: transparent;\n"
"	border: none;\n"
"	padding: 0;\n"
"}")
        self.SelectSequenceButton.setIcon(icon)
        self.ConfirmSelection = QDialogButtonBox(self.FileSelectionFrame)
        self.ConfirmSelection.setObjectName(u"ConfirmSelection")
        self.ConfirmSelection.setGeometry(QRect(0, 85, 260, 24))
        sizePolicy.setHeightForWidth(self.ConfirmSelection.sizePolicy().hasHeightForWidth())
        self.ConfirmSelection.setSizePolicy(sizePolicy)
        self.ConfirmSelection.setFont(font1)
        self.ConfirmSelection.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ConfirmSelection.setTabletTracking(False)
        self.ConfirmSelection.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.ConfirmSelection.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.ConfirmSelection.setAutoFillBackground(False)
        self.ConfirmSelection.setOrientation(Qt.Orientation.Horizontal)
        self.ConfirmSelection.setStandardButtons(QDialogButtonBox.StandardButton.Reset|QDialogButtonBox.StandardButton.Save)
        self.ConfirmSelection.setCenterButtons(True)
        self.saveLocationFrame = QFrame(self.SettingsPage)
        self.saveLocationFrame.setObjectName(u"saveLocationFrame")
        self.saveLocationFrame.setGeometry(QRect(20, 145, 260, 105))
        self.saveLocationFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.saveLocationFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.saveLocationLabel = QLabel(self.saveLocationFrame)
        self.saveLocationLabel.setObjectName(u"saveLocationLabel")
        self.saveLocationLabel.setGeometry(QRect(0, 0, 260, 40))
        self.saveLocationLabel.setFont(font)
        self.saveLocationLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.RAMorEEPROMwidget = QWidget(self.saveLocationFrame)
        self.RAMorEEPROMwidget.setObjectName(u"RAMorEEPROMwidget")
        self.RAMorEEPROMwidget.setGeometry(QRect(0, 45, 260, 16))
        self.SaveToDeviceRAM = QCheckBox(self.RAMorEEPROMwidget)
        self.SaveToDeviceRAM.setObjectName(u"SaveToDeviceRAM")
        self.SaveToDeviceRAM.setGeometry(QRect(70, 0, 50, 16))
        self.SaveToDeviceRAM.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.SaveToDeviceEEPROM = QCheckBox(self.RAMorEEPROMwidget)
        self.SaveToDeviceEEPROM.setObjectName(u"SaveToDeviceEEPROM")
        self.SaveToDeviceEEPROM.setGeometry(QRect(150, 0, 71, 16))
        self.SaveToDeviceEEPROM.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.SaveToDeviceEEPROM.setChecked(False)
        self.SaveToDeviceEEPROM.setTristate(False)
        self.SaveSettingsButton = QPushButton(self.saveLocationFrame)
        self.SaveSettingsButton.setObjectName(u"SaveSettingsButton")
        self.SaveSettingsButton.setGeometry(QRect(92, 71, 76, 24))
        self.SaveSettingsButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.SaveSettingsButton.setAutoFillBackground(False)
        self.SaveSettingsButton.setStyleSheet(u"")
        self.SaveSettingsButton.setAutoDefault(False)
        self.SaveSettingsButton.setFlat(False)
        self.viewDeviceSettingsFrame = QFrame(self.SettingsPage)
        self.viewDeviceSettingsFrame.setObjectName(u"viewDeviceSettingsFrame")
        self.viewDeviceSettingsFrame.setGeometry(QRect(20, 255, 260, 95))
        self.viewDeviceSettingsFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.viewDeviceSettingsFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.ViewDeviceSettingsLabel = QLabel(self.viewDeviceSettingsFrame)
        self.ViewDeviceSettingsLabel.setObjectName(u"ViewDeviceSettingsLabel")
        self.ViewDeviceSettingsLabel.setGeometry(QRect(0, 0, 260, 40))
        self.ViewDeviceSettingsLabel.setFont(font)
        self.ViewDeviceSettingsLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.DeviceEepromLabel = QLabel(self.viewDeviceSettingsFrame)
        self.DeviceEepromLabel.setObjectName(u"DeviceEepromLabel")
        self.DeviceEepromLabel.setGeometry(QRect(0, 40, 80, 16))
        self.DeviceEepromLabel.setFont(font2)
        self.DeviceEepromLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.SaveEepromSequence = QPushButton(self.viewDeviceSettingsFrame)
        self.SaveEepromSequence.setObjectName(u"SaveEepromSequence")
        self.SaveEepromSequence.setGeometry(QRect(110, 40, 16, 16))
        sizePolicy.setHeightForWidth(self.SaveEepromSequence.sizePolicy().hasHeightForWidth())
        self.SaveEepromSequence.setSizePolicy(sizePolicy)
        self.SaveEepromSequence.setFont(font3)
        self.SaveEepromSequence.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.SaveEepromSequence.setStyleSheet(u"QPushButton{\n"
"	background-color: transparent;\n"
"	border: none;\n"
"	padding: 0;\n"
"}")
        self.SaveEepromSequence.setIcon(icon)
        self.SaveEepromSequence.setIconSize(QSize(16, 16))
        self.SaveEepromSequence.setCheckable(False)
        self.DeviceRamLabel = QLabel(self.viewDeviceSettingsFrame)
        self.DeviceRamLabel.setObjectName(u"DeviceRamLabel")
        self.DeviceRamLabel.setGeometry(QRect(0, 60, 80, 16))
        self.DeviceRamLabel.setFont(font2)
        self.DeviceRamLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.SaveRamSequence = QPushButton(self.viewDeviceSettingsFrame)
        self.SaveRamSequence.setObjectName(u"SaveRamSequence")
        self.SaveRamSequence.setGeometry(QRect(110, 60, 16, 16))
        sizePolicy.setHeightForWidth(self.SaveRamSequence.sizePolicy().hasHeightForWidth())
        self.SaveRamSequence.setSizePolicy(sizePolicy)
        self.SaveRamSequence.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.SaveRamSequence.setStyleSheet(u"QPushButton{\n"
"	background-color: transparent;\n"
"	border: none;\n"
"	padding: 0;\n"
"}")
        self.SaveRamSequence.setIcon(icon)
        self.homeFromFileWidget = QWidget(self.SettingsPage)
        self.homeFromFileWidget.setObjectName(u"homeFromFileWidget")
        self.homeFromFileWidget.setGeometry(QRect(20, 355, 260, 24))
        self.homeFromFiles = QPushButton(self.homeFromFileWidget)
        self.homeFromFiles.setObjectName(u"homeFromFiles")
        self.homeFromFiles.setGeometry(QRect(92, 0, 76, 24))
        self.homeFromFiles.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.stackedWidget.addWidget(self.SettingsPage)
        self.MainPage = QWidget()
        self.MainPage.setObjectName(u"MainPage")
        self.PropertiesFrame = QFrame(self.MainPage)
        self.PropertiesFrame.setObjectName(u"PropertiesFrame")
        self.PropertiesFrame.setGeometry(QRect(20, 20, 260, 330))
        self.PropertiesFrame.setAutoFillBackground(False)
        self.PropertiesFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.PropertiesFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.SetSequence = QLabel(self.PropertiesFrame)
        self.SetSequence.setObjectName(u"SetSequence")
        self.SetSequence.setGeometry(QRect(0, 0, 260, 40))
        self.SetSequence.setFont(font)
        self.SetSequence.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.MetadataFrame = QFrame(self.PropertiesFrame)
        self.MetadataFrame.setObjectName(u"MetadataFrame")
        self.MetadataFrame.setGeometry(QRect(20, 40, 220, 120))
        self.MetadataFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.MetadataFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.metadataLabelsWidget = QWidget(self.MetadataFrame)
        self.metadataLabelsWidget.setObjectName(u"metadataLabelsWidget")
        self.metadataLabelsWidget.setGeometry(QRect(0, 0, 70, 116))
        self.ArtistLabel = QLabel(self.metadataLabelsWidget)
        self.ArtistLabel.setObjectName(u"ArtistLabel")
        self.ArtistLabel.setGeometry(QRect(0, 10, 70, 16))
        self.ArtistLabel.setFont(font2)
        self.ArtistLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.NameLabel = QLabel(self.metadataLabelsWidget)
        self.NameLabel.setObjectName(u"NameLabel")
        self.NameLabel.setGeometry(QRect(0, 30, 70, 16))
        self.NameLabel.setFont(font2)
        self.NameLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.BPMLabel = QLabel(self.metadataLabelsWidget)
        self.BPMLabel.setObjectName(u"BPMLabel")
        self.BPMLabel.setGeometry(QRect(0, 50, 70, 16))
        self.BPMLabel.setFont(font2)
        self.BPMLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.OffsetLabel = QLabel(self.metadataLabelsWidget)
        self.OffsetLabel.setObjectName(u"OffsetLabel")
        self.OffsetLabel.setGeometry(QRect(0, 70, 70, 16))
        self.OffsetLabel.setFont(font2)
        self.OffsetLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.DifficultyLabel = QLabel(self.metadataLabelsWidget)
        self.DifficultyLabel.setObjectName(u"DifficultyLabel")
        self.DifficultyLabel.setGeometry(QRect(0, 90, 70, 16))
        self.DifficultyLabel.setFont(font2)
        self.DifficultyLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.MetadataLabelsWidget = QWidget(self.MetadataFrame)
        self.MetadataLabelsWidget.setObjectName(u"MetadataLabelsWidget")
        self.MetadataLabelsWidget.setGeometry(QRect(70, 0, 140, 116))
        self.BPMDisplay = QLabel(self.MetadataLabelsWidget)
        self.BPMDisplay.setObjectName(u"BPMDisplay")
        self.BPMDisplay.setGeometry(QRect(10, 50, 130, 16))
        self.OffsetDisplay = QLabel(self.MetadataLabelsWidget)
        self.OffsetDisplay.setObjectName(u"OffsetDisplay")
        self.OffsetDisplay.setGeometry(QRect(10, 70, 130, 16))
        self.DifficultyDisplay = QLabel(self.MetadataLabelsWidget)
        self.DifficultyDisplay.setObjectName(u"DifficultyDisplay")
        self.DifficultyDisplay.setGeometry(QRect(10, 90, 130, 16))
        self.audioPlayerWidget = QWidget(self.PropertiesFrame)
        self.audioPlayerWidget.setObjectName(u"audioPlayerWidget")
        self.audioPlayerWidget.setGeometry(QRect(0, 190, 260, 110))
        self.ReplayAudio = QPushButton(self.audioPlayerWidget)
        self.ReplayAudio.setObjectName(u"ReplayAudio")
        self.ReplayAudio.setGeometry(QRect(60, 10, 40, 40))
        font4 = QFont()
        font4.setBold(False)
        self.ReplayAudio.setFont(font4)
        self.ReplayAudio.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ReplayAudio.setAutoFillBackground(False)
        self.ReplayAudio.setStyleSheet(u"QPushButton{\n"
"	background-color: transparent;\n"
"	border: none;\n"
"	padding: 0;\n"
"}")
        self.ReplayAudio.setIconSize(QSize(40, 40))
        self.ReplayAudio.setCheckable(False)
        self.ReplayAudio.setAutoDefault(False)
        self.ReplayAudio.setFlat(False)
        self.AudioPlayback = QPushButton(self.audioPlayerWidget)
        self.AudioPlayback.setObjectName(u"AudioPlayback")
        self.AudioPlayback.setGeometry(QRect(110, 10, 40, 40))
        self.AudioPlayback.setFont(font4)
        self.AudioPlayback.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.AudioPlayback.setAutoFillBackground(False)
        self.AudioPlayback.setStyleSheet(u"QPushButton{\n"
"	background-color: transparent;\n"
"	border: none;\n"
"	padding: 0;\n"
"}")
        self.AudioPlayback.setIconSize(QSize(40, 40))
        self.AudioPlayback.setCheckable(False)
        self.AudioPlayback.setChecked(False)
        self.AudioPlayback.setAutoDefault(False)
        self.AudioPlayback.setFlat(True)
        self.elapsed = QLabel(self.audioPlayerWidget)
        self.elapsed.setObjectName(u"elapsed")
        self.elapsed.setGeometry(QRect(160, 50, 70, 16))
        self.progressBar = QProgressBar(self.audioPlayerWidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(20, 70, 220, 23))
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(False)
        self.volumeAdjustWidget = QWidget(self.audioPlayerWidget)
        self.volumeAdjustWidget.setObjectName(u"volumeAdjustWidget")
        self.volumeAdjustWidget.setGeometry(QRect(150, 90, 101, 20))
        sizePolicy.setHeightForWidth(self.volumeAdjustWidget.sizePolicy().hasHeightForWidth())
        self.volumeAdjustWidget.setSizePolicy(sizePolicy)
        self.volumeAdjustWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.volumeSlider = QSlider(self.volumeAdjustWidget)
        self.volumeSlider.setObjectName(u"volumeSlider")
        self.volumeSlider.setGeometry(QRect(24, 0, 71, 20))
        sizePolicy.setHeightForWidth(self.volumeSlider.sizePolicy().hasHeightForWidth())
        self.volumeSlider.setSizePolicy(sizePolicy)
        self.volumeSlider.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.volumeSlider.setMouseTracking(False)
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setSingleStep(5)
        self.volumeSlider.setValue(70)
        self.volumeSlider.setSliderPosition(70)
        self.volumeSlider.setOrientation(Qt.Orientation.Horizontal)
        self.volumeSlider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.volumeIcon = QLabel(self.volumeAdjustWidget)
        self.volumeIcon.setObjectName(u"volumeIcon")
        self.volumeIcon.setGeometry(QRect(0, 0, 20, 20))
        self.volumeIcon.setAutoFillBackground(False)
        self.volumeIcon.setStyleSheet(u"")
        self.volumeIcon.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.secretButton = QPushButton(self.PropertiesFrame)
        self.secretButton.setObjectName(u"secretButton")
        self.secretButton.setGeometry(QRect(230, 10, 16, 16))
        self.secretButton.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.secretButton.setStyleSheet(u"QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: transparent;\n"
"    }")
        self.homeFromInfo = QPushButton(self.MainPage)
        self.homeFromInfo.setObjectName(u"homeFromInfo")
        self.homeFromInfo.setGeometry(QRect(112, 355, 76, 24))
        self.homeFromInfo.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.stackedWidget.addWidget(self.MainPage)
        self.TimingWindowsPage = QWidget()
        self.TimingWindowsPage.setObjectName(u"TimingWindowsPage")
        self.CurrentSettings = QFrame(self.TimingWindowsPage)
        self.CurrentSettings.setObjectName(u"CurrentSettings")
        self.CurrentSettings.setGeometry(QRect(20, 20, 260, 230))
        self.CurrentSettings.setFrameShape(QFrame.Shape.StyledPanel)
        self.CurrentSettings.setFrameShadow(QFrame.Shadow.Raised)
        self.TimingWindowsSettingsLabel = QLabel(self.CurrentSettings)
        self.TimingWindowsSettingsLabel.setObjectName(u"TimingWindowsSettingsLabel")
        self.TimingWindowsSettingsLabel.setGeometry(QRect(0, 0, 260, 40))
        font5 = QFont()
        font5.setFamilies([u"Segoe UI"])
        font5.setPointSize(12)
        font5.setBold(True)
        font5.setUnderline(False)
        self.TimingWindowsSettingsLabel.setFont(font5)
        self.TimingWindowsSettingsLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.TimingWindowTable = QTableWidget(self.CurrentSettings)
        if (self.TimingWindowTable.columnCount() < 1):
            self.TimingWindowTable.setColumnCount(1)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setFont(font2);
        self.TimingWindowTable.setHorizontalHeaderItem(0, __qtablewidgetitem)
        if (self.TimingWindowTable.rowCount() < 5):
            self.TimingWindowTable.setRowCount(5)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem1.setFont(font2);
        self.TimingWindowTable.setVerticalHeaderItem(0, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem2.setFont(font2);
        self.TimingWindowTable.setVerticalHeaderItem(1, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem3.setFont(font2);
        self.TimingWindowTable.setVerticalHeaderItem(2, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        __qtablewidgetitem4.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem4.setFont(font2);
        self.TimingWindowTable.setVerticalHeaderItem(3, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem5.setFont(font2);
        self.TimingWindowTable.setVerticalHeaderItem(4, __qtablewidgetitem5)
        font6 = QFont()
        font6.setPointSize(10)
        font6.setBold(False)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem6.setFont(font6);
        __qtablewidgetitem6.setFlags(Qt.ItemIsSelectable|Qt.ItemIsUserCheckable|Qt.ItemIsEnabled);
        self.TimingWindowTable.setItem(0, 0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem7.setFont(font1);
        self.TimingWindowTable.setItem(1, 0, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        __qtablewidgetitem8.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem8.setFont(font1);
        self.TimingWindowTable.setItem(2, 0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        __qtablewidgetitem9.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem9.setFont(font1);
        self.TimingWindowTable.setItem(3, 0, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        __qtablewidgetitem10.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem10.setFont(font1);
        __qtablewidgetitem10.setFlags(Qt.ItemIsDragEnabled|Qt.ItemIsDropEnabled|Qt.ItemIsUserCheckable|Qt.ItemIsEnabled);
        self.TimingWindowTable.setItem(4, 0, __qtablewidgetitem10)
        self.TimingWindowTable.setObjectName(u"TimingWindowTable")
        self.TimingWindowTable.setEnabled(True)
        self.TimingWindowTable.setGeometry(QRect(20, 40, 220, 176))
        sizePolicy.setHeightForWidth(self.TimingWindowTable.sizePolicy().hasHeightForWidth())
        self.TimingWindowTable.setSizePolicy(sizePolicy)
        self.TimingWindowTable.setFont(font6)
        self.TimingWindowTable.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.CrossCursor))
        self.TimingWindowTable.setAutoFillBackground(False)
        self.TimingWindowTable.setFrameShape(QFrame.Shape.NoFrame)
        self.TimingWindowTable.setFrameShadow(QFrame.Shadow.Sunken)
        self.TimingWindowTable.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.TimingWindowTable.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.TimingWindowTable.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.TimingWindowTable.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.TimingWindowTable.setDragDropOverwriteMode(False)
        self.TimingWindowTable.setAlternatingRowColors(True)
        self.TimingWindowTable.setShowGrid(True)
        self.TimingWindowTable.setGridStyle(Qt.PenStyle.SolidLine)
        self.TimingWindowTable.setSortingEnabled(False)
        self.TimingWindowTable.setWordWrap(True)
        self.TimingWindowTable.setCornerButtonEnabled(False)
        self.TimingWindowTable.horizontalHeader().setVisible(True)
        self.TimingWindowTable.horizontalHeader().setMinimumSectionSize(34)
        self.TimingWindowTable.horizontalHeader().setDefaultSectionSize(164)
        self.TimingWindowTable.horizontalHeader().setProperty(u"showSortIndicator", False)
        self.TimingWindowTable.horizontalHeader().setStretchLastSection(False)
        self.TimingWindowTable.verticalHeader().setVisible(True)
        self.TimingWindowTable.verticalHeader().setCascadingSectionResizes(False)
        self.TimingWindowTable.verticalHeader().setProperty(u"showSortIndicator", False)
        self.TimingWindowTable.verticalHeader().setStretchLastSection(False)
        self.resetDeviceToDefaults = QPushButton(self.CurrentSettings)
        self.resetDeviceToDefaults.setObjectName(u"resetDeviceToDefaults")
        self.resetDeviceToDefaults.setGeometry(QRect(10, 10, 16, 16))
        sizePolicy.setHeightForWidth(self.resetDeviceToDefaults.sizePolicy().hasHeightForWidth())
        self.resetDeviceToDefaults.setSizePolicy(sizePolicy)
        self.resetDeviceToDefaults.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.resetDeviceToDefaults.setStyleSheet(u"QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: transparent;\n"
"    }")
        self.timingWindowsAdjustFrame = QFrame(self.TimingWindowsPage)
        self.timingWindowsAdjustFrame.setObjectName(u"timingWindowsAdjustFrame")
        self.timingWindowsAdjustFrame.setGeometry(QRect(20, 260, 260, 90))
        self.timingWindowsAdjustFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.timingWindowsAdjustFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.SaveChoice = QDialogButtonBox(self.timingWindowsAdjustFrame)
        self.SaveChoice.setObjectName(u"SaveChoice")
        self.SaveChoice.setGeometry(QRect(0, 46, 260, 24))
        self.SaveChoice.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.SaveChoice.setOrientation(Qt.Orientation.Horizontal)
        self.SaveChoice.setStandardButtons(QDialogButtonBox.StandardButton.Apply|QDialogButtonBox.StandardButton.Reset|QDialogButtonBox.StandardButton.SaveAll)
        self.SaveChoice.setCenterButtons(True)
        self.timingSliderWidget = QWidget(self.timingWindowsAdjustFrame)
        self.timingSliderWidget.setObjectName(u"timingSliderWidget")
        self.timingSliderWidget.setGeometry(QRect(0, 20, 260, 16))
        self.horizontalSlider = QSlider(self.timingSliderWidget)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(70, 0, 120, 16))
        self.horizontalSlider.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(500)
        self.horizontalSlider.setOrientation(Qt.Orientation.Horizontal)
        self.ValueFromSlider = QLabel(self.timingSliderWidget)
        self.ValueFromSlider.setObjectName(u"ValueFromSlider")
        self.ValueFromSlider.setGeometry(QRect(200, 0, 50, 16))
        font7 = QFont()
        font7.setFamilies([u"Arial"])
        font7.setPointSize(9)
        font7.setBold(True)
        self.ValueFromSlider.setFont(font7)
        self.ValueFromSlider.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.homeFromTW = QPushButton(self.TimingWindowsPage)
        self.homeFromTW.setObjectName(u"homeFromTW")
        self.homeFromTW.setGeometry(QRect(112, 355, 76, 24))
        self.stackedWidget.addWidget(self.TimingWindowsPage)
        self.mysteryPage = QWidget()
        self.mysteryPage.setObjectName(u"mysteryPage")
        self.mysteryWidget = QWidget(self.mysteryPage)
        self.mysteryWidget.setObjectName(u"mysteryWidget")
        self.mysteryWidget.setGeometry(QRect(20, 20, 260, 330))
        self.mysteryLabel = QLabel(self.mysteryWidget)
        self.mysteryLabel.setObjectName(u"mysteryLabel")
        self.mysteryLabel.setGeometry(QRect(0, 0, 260, 173))
        self.endCredits = QPlainTextEdit(self.mysteryWidget)
        self.endCredits.setObjectName(u"endCredits")
        self.endCredits.setGeometry(QRect(0, 200, 260, 115))
        sizePolicy.setHeightForWidth(self.endCredits.sizePolicy().hasHeightForWidth())
        self.endCredits.setSizePolicy(sizePolicy)
        font8 = QFont()
        font8.setBold(False)
        font8.setItalic(False)
        self.endCredits.setFont(font8)
        self.endCredits.setAcceptDrops(False)
        self.endCredits.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.endCredits.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.endCredits.setReadOnly(True)
        self.AudioSynchronisation = QCheckBox(self.mysteryWidget)
        self.AudioSynchronisation.setObjectName(u"AudioSynchronisation")
        self.AudioSynchronisation.setGeometry(QRect(90, 180, 91, 20))
        self.AudioSynchronisation.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.homeFromMystery = QPushButton(self.mysteryPage)
        self.homeFromMystery.setObjectName(u"homeFromMystery")
        self.homeFromMystery.setGeometry(QRect(112, 355, 76, 24))
        self.stackedWidget.addWidget(self.mysteryPage)
        self.Title_TPMANIA = QLabel(self.centralwidget)
        self.Title_TPMANIA.setObjectName(u"Title_TPMANIA")
        self.Title_TPMANIA.setGeometry(QRect(0, 0, 300, 40))
        font9 = QFont()
        font9.setFamilies([u"ROG Fonts"])
        font9.setPointSize(24)
        font9.setBold(False)
        font9.setItalic(False)
        self.Title_TPMANIA.setFont(font9)
        self.Title_TPMANIA.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.Title_TPMANIA.setAutoFillBackground(False)
        self.Title_TPMANIA.setAlignment(Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)
        self.threadIndicator = QLabel(self.centralwidget)
        self.threadIndicator.setObjectName(u"threadIndicator")
        self.threadIndicator.setGeometry(QRect(5, 5, 8, 8))
        self.threadIndicator.setAutoFillBackground(False)
        self.threadIndicator.setStyleSheet(u"")
        self.threadIndicator.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.readyIndicator = QLabel(self.centralwidget)
        self.readyIndicator.setObjectName(u"readyIndicator")
        self.readyIndicator.setGeometry(QRect(5, 5, 8, 8))
        self.readyIndicator.setAutoFillBackground(False)
        self.readyIndicator.setStyleSheet(u"")
        self.readyIndicator.setAlignment(Qt.AlignmentFlag.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)
        self.SaveSettingsButton.setDefault(False)
        self.ReplayAudio.setDefault(False)
        self.AudioPlayback.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
#if QT_CONFIG(tooltip)
        self.fileSelection.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.fileSelection.setText(QCoreApplication.translate("MainWindow", u"File Selection", None))
#if QT_CONFIG(tooltip)
        self.metadataDisplay.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.metadataDisplay.setText(QCoreApplication.translate("MainWindow", u"Metadata Display", None))
#if QT_CONFIG(tooltip)
        self.timingWindows.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.timingWindows.setText(QCoreApplication.translate("MainWindow", u"Timing Windows", None))
#if QT_CONFIG(tooltip)
        self.mysteryButton.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.mysteryButton.setText(QCoreApplication.translate("MainWindow", u"\U0001f512", None))
        self.SerialPortLabel.setText(QCoreApplication.translate("MainWindow", u"Serial Port:", None))
        self.SerialPorts.setItemText(0, QCoreApplication.translate("MainWindow", u"--select", None))

#if QT_CONFIG(tooltip)
        self.SerialPorts.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.SerialPorts.setPlaceholderText(QCoreApplication.translate("MainWindow", u"--select", None))
#if QT_CONFIG(tooltip)
        self.ConfigurePort.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.AudioLabel.setText(QCoreApplication.translate("MainWindow", u"Audio:", None))
        self.SequenceLabel.setText(QCoreApplication.translate("MainWindow", u"Sequence:", None))
        self.HeaderFileSelection.setText(QCoreApplication.translate("MainWindow", u"File Selection", None))
#if QT_CONFIG(tooltip)
        self.SelectAudioButton.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.SelectAudioButton.setText("")
#if QT_CONFIG(tooltip)
        self.SelectSequenceButton.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.SelectSequenceButton.setText("")
        self.saveLocationLabel.setText(QCoreApplication.translate("MainWindow", u"Save Location", None))
#if QT_CONFIG(tooltip)
        self.SaveToDeviceRAM.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.SaveToDeviceRAM.setText(QCoreApplication.translate("MainWindow", u"RAM", None))
#if QT_CONFIG(tooltip)
        self.SaveToDeviceEEPROM.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.SaveToDeviceEEPROM.setText(QCoreApplication.translate("MainWindow", u"EEPROM", None))
#if QT_CONFIG(tooltip)
        self.SaveSettingsButton.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.SaveSettingsButton.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.ViewDeviceSettingsLabel.setText(QCoreApplication.translate("MainWindow", u"View Device Settings", None))
        self.DeviceEepromLabel.setText(QCoreApplication.translate("MainWindow", u"EEPROM:", None))
#if QT_CONFIG(tooltip)
        self.SaveEepromSequence.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.SaveEepromSequence.setText("")
        self.DeviceRamLabel.setText(QCoreApplication.translate("MainWindow", u"RAM:", None))
#if QT_CONFIG(tooltip)
        self.SaveRamSequence.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.SaveRamSequence.setText("")
#if QT_CONFIG(tooltip)
        self.homeFromFiles.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.homeFromFiles.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.SetSequence.setText(QCoreApplication.translate("MainWindow", u"Sequence Info Display", None))
        self.ArtistLabel.setText(QCoreApplication.translate("MainWindow", u"Artist:", None))
        self.NameLabel.setText(QCoreApplication.translate("MainWindow", u"Name:", None))
        self.BPMLabel.setText(QCoreApplication.translate("MainWindow", u"BPM:", None))
        self.OffsetLabel.setText(QCoreApplication.translate("MainWindow", u"Offset:", None))
        self.DifficultyLabel.setText(QCoreApplication.translate("MainWindow", u"Difficulty:", None))
        self.BPMDisplay.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.OffsetDisplay.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.DifficultyDisplay.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
#if QT_CONFIG(tooltip)
        self.ReplayAudio.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.ReplayAudio.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.ReplayAudio.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.ReplayAudio.setText("")
#if QT_CONFIG(tooltip)
        self.AudioPlayback.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.AudioPlayback.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.AudioPlayback.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.AudioPlayback.setText("")
        self.elapsed.setText(QCoreApplication.translate("MainWindow", u"00:00 / 00:00", None))
        self.progressBar.setFormat(QCoreApplication.translate("MainWindow", u"%p%", None))
#if QT_CONFIG(tooltip)
        self.volumeSlider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.volumeIcon.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.volumeIcon.setText("")
        self.secretButton.setText("")
#if QT_CONFIG(tooltip)
        self.homeFromInfo.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.homeFromInfo.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.TimingWindowsSettingsLabel.setText(QCoreApplication.translate("MainWindow", u"Timing Windows Settings", None))
        ___qtablewidgetitem = self.TimingWindowTable.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Duration (ms)", None));
        ___qtablewidgetitem1 = self.TimingWindowTable.verticalHeaderItem(0)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Perfect!", None));
        ___qtablewidgetitem2 = self.TimingWindowTable.verticalHeaderItem(1)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Good!", None));
        ___qtablewidgetitem3 = self.TimingWindowTable.verticalHeaderItem(2)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"OK", None));
        ___qtablewidgetitem4 = self.TimingWindowTable.verticalHeaderItem(3)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Poor", None));
        ___qtablewidgetitem5 = self.TimingWindowTable.verticalHeaderItem(4)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Miss", None));

        __sortingEnabled = self.TimingWindowTable.isSortingEnabled()
        self.TimingWindowTable.setSortingEnabled(False)
        self.TimingWindowTable.setSortingEnabled(__sortingEnabled)

        self.resetDeviceToDefaults.setText("")
#if QT_CONFIG(tooltip)
        self.horizontalSlider.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.ValueFromSlider.setText(QCoreApplication.translate("MainWindow", u"250 ms", None))
#if QT_CONFIG(tooltip)
        self.homeFromTW.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.homeFromTW.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.mysteryLabel.setText("")
        self.endCredits.setPlainText(QCoreApplication.translate("MainWindow", u"ENGG2800 Team 7\n"
"\n"
"Jack Scotton:               PC Software\n"
"Mohamed Zoheiry:     Firmware / Comms\n"
"Bryan Jun Qian Lau:    Firmware / Game Logic\n"
"Yi He:                          Hardware / PCB", None))
#if QT_CONFIG(tooltip)
        self.AudioSynchronisation.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.AudioSynchronisation.setText(QCoreApplication.translate("MainWindow", u"Audio Sync", None))
#if QT_CONFIG(tooltip)
        self.homeFromMystery.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.homeFromMystery.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.Title_TPMANIA.setText(QCoreApplication.translate("MainWindow", u"TPMANIA", None))
#if QT_CONFIG(tooltip)
        self.threadIndicator.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.threadIndicator.setText("")
#if QT_CONFIG(tooltip)
        self.readyIndicator.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.readyIndicator.setText("")
    # retranslateUi

